apiVersion: v1
kind: Service
metadata:
  name: evalservice
  labels:
    run: evalservice
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    run: evalservice
  type: LoadBalancer